# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\active_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 181)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon_app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.btnActive = QtWidgets.QPushButton(Dialog)
        self.btnActive.setGeometry(QtCore.QRect(120, 60, 75, 23))
        self.btnActive.setObjectName("btnActive")
        self.edtActiveKey = QtWidgets.QLineEdit(Dialog)
        self.edtActiveKey.setGeometry(QtCore.QRect(10, 30, 301, 20))
        self.edtActiveKey.setObjectName("edtActiveKey")
        self.lblMessage = QtWidgets.QLabel(Dialog)
        self.lblMessage.setGeometry(QtCore.QRect(10, 100, 561, 20))
        self.lblMessage.setText("")
        self.lblMessage.setObjectName("lblMessage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Active Key"))
        self.btnActive.setText(_translate("Dialog", "Active"))
        self.edtActiveKey.setPlaceholderText(_translate("Dialog", "Enter your key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
