# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 311)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.btnStart.setObjectName("btnStart")
        self.edtOriginalFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.edtOriginalFolder.setGeometry(QtCore.QRect(100, 10, 511, 20))
        self.edtOriginalFolder.setObjectName("edtOriginalFolder")
        self.lblOriginalFolder = QtWidgets.QLabel(self.centralwidget)
        self.lblOriginalFolder.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.lblOriginalFolder.setObjectName("lblOriginalFolder")
        self.btnBrowserOriginal = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowserOriginal.setGeometry(QtCore.QRect(620, 10, 75, 23))
        self.btnBrowserOriginal.setObjectName("btnBrowserOriginal")
        self.edtResizeFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.edtResizeFolder.setGeometry(QtCore.QRect(100, 40, 511, 20))
        self.edtResizeFolder.setObjectName("edtResizeFolder")
        self.btnBrowserResize = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowserResize.setGeometry(QtCore.QRect(620, 40, 75, 23))
        self.btnBrowserResize.setObjectName("btnBrowserResize")
        self.lblResizeFolder = QtWidgets.QLabel(self.centralwidget)
        self.lblResizeFolder.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.lblResizeFolder.setObjectName("lblResizeFolder")
        self.edtLogs = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.edtLogs.setGeometry(QtCore.QRect(10, 150, 601, 101))
        self.edtLogs.setObjectName("edtLogs")
        self.lblParallelHandling = QtWidgets.QLabel(self.centralwidget)
        self.lblParallelHandling.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.lblParallelHandling.setObjectName("lblParallelHandling")
        self.edtParallelHandling = QtWidgets.QLineEdit(self.centralwidget)
        self.edtParallelHandling.setGeometry(QtCore.QRect(100, 70, 61, 20))
        self.edtParallelHandling.setObjectName("edtParallelHandling")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.lblOriginalFolder.setText(_translate("MainWindow", "Original folder:"))
        self.btnBrowserOriginal.setText(_translate("MainWindow", "Browser..."))
        self.btnBrowserResize.setText(_translate("MainWindow", "Browser..."))
        self.lblResizeFolder.setText(_translate("MainWindow", "Resize folder:"))
        self.lblParallelHandling.setText(_translate("MainWindow", "Parallel handling:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
