# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtFolderPath = QtWidgets.QLabel(self.centralwidget)
        self.txtFolderPath.setGeometry(QtCore.QRect(10, 30, 291, 16))
        self.txtFolderPath.setObjectName("txtFolderPath")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 117, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFolder = QtWidgets.QLabel(self.layoutWidget)
        self.lblFolder.setObjectName("lblFolder")
        self.horizontalLayout.addWidget(self.lblFolder)
        self.btnBrowser = QtWidgets.QPushButton(self.layoutWidget)
        self.btnBrowser.setObjectName("btnBrowser")
        self.horizontalLayout.addWidget(self.btnBrowser)
        self.btnRemoveDuplicate = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoveDuplicate.setGeometry(QtCore.QRect(10, 60, 121, 23))
        self.btnRemoveDuplicate.setObjectName("btnRemoveDuplicate")
        self.lblProcess = QtWidgets.QLabel(self.centralwidget)
        self.lblProcess.setGeometry(QtCore.QRect(10, 90, 291, 16))
        self.lblProcess.setText("")
        self.lblProcess.setObjectName("lblProcess")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtFolderPath.setText(_translate("MainWindow", "N/A"))
        self.lblFolder.setText(_translate("MainWindow", "Folder:"))
        self.btnBrowser.setText(_translate("MainWindow", "Browser..."))
        self.btnRemoveDuplicate.setText(_translate("MainWindow", "Remove duplicate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
